### PR TITLE
fix: resolution of an index.d.ts inside a directory

### LINKED ISSUE #99: Export of directories with an index.d.ts not handled correctly
It seems that the components-generator does not handle exports of directories with an index.d.ts

Directory structure:
- `index.d.ts`
- `/directory_1`
  - `/index.d.ts`
  - `/SomeFile.d.ts`
- `/directory_2`
  - `/index.d.ts`
  - `/SomeFile2.d.ts`
 
Example index.d.ts (root)
```typescript
export * from './directory_1';
export * from './directory_2';
```

Running the generator will throw the following error:
```text
[Components.js] info: Generating components for 1 package
ENOENT: no such file or directory, open '...\directory_1.d.ts
```
There is indeed no directory_1.d.ts, but there is a '..\directory_1\index.d.ts'

If I change the index.d.ts in the root to:
```typescript
export * from './directory_1/index';
export * from './directory_2/index';
```
it will correctly generate the components

I might have a PR that I am testing that could fix this issue by modifying: https://github.com/LinkedSoftwareDependencies/Components-Generator.js/blob/master/lib/resolution/ResolutionContext.ts#L67-L69
to include a fallback. But I am not entirely sure it it would be the best place to fix it here, as the context of the relative paths within that index are incorrect (i.e. if you have an `export * from './SomeFile'` in `./directory_1/index.d.ts` it will try to load `./SomeFile` instead of `./directory_1/SomeFile`

### PR DESCRIPTION
**Pull request by Maximvdw**
Closes #99 

This PR adds an additional check that verifies if the d.ts of a specific exported filePath exists. If not, it will attempt to treat the filePath as a directory.

More information in issue #99 

Workflow run: https://github.com/Maximvdw/Components-Generator.js/actions/runs/2227906346

### CODE REVIEW

File: lib/parse/ClassLoader.ts [hunk 1]
```diff
@@ -457,11 +457,17 @@ export class ClassLoader {
...
+   * @returns {Promise<ClassElements & { resolvedPath: string }>} Promise of the class elements along with
+   * the resolved file path that was used to load these class elements.
    */
-  public async loadClassElements(packageName: string, fileName: string): Promise<ClassElements> {
-    const ast = await this.resolutionContext.parseTypescriptFile(fileName);
-    return this.getClassElements(packageName, fileName, ast);
+  public async loadClassElements(packageName: string, filePath: string): Promise<
+  ClassElements & { resolvedPath: string }
+  > {
+    const resolvedPath = await this.resolutionContext.resolveTypesPath(filePath);
```
Comment (Maximvdw) [inline lib/parse/ClassLoader.ts:467]: Path resolution has been added here instead of ClassFinder.ts as it seemed the most elegant solution for now. The idea is that `loadClassElements` on a filePath gives you the class elements and the path used to obtain them

**Comment by rubensworks** [comment]
This looks perfect, thanks!
Also tested in some other projects, and everything seems to work as intended.

Released as 3.0.3.
